import Head from "next/head";
import Layout from "@layout";
import { Hero, Services, About, Points } from "@components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Points />
        <Services />
        <About />
      </Layout>
    </>
  );
}
